normative statements: Conformance section
w3c/did-core pull request #426
Opened 2020-10-03 18:49 UTC by rhiaro

Removes untestable normative language from Conformance section, towards #384

2020-10-07 16:38 UTC, brentzundel approved these changes
minor nits, otherwise LTGM

2020-10-07 16:38 UTC, brentzundel commented on index.html
> +in Section <a href="#identifier"></a> and complies with relevant normative
```suggestion
in Section <a href="#identifier"></a>which complies with relevant normative
```

2020-10-07 16:38 UTC, brentzundel commented on index.html
> +model described in this specification and complies with with the relevant
```suggestion
model described in this specification which complies with with the relevant
```

2020-10-08 13:38 UTC, msporny requested changes
Approved as long as the changes that @brentzundel requested are made.

2020-10-08 22:59 UTC, peacekeeper approved these changes
+1 to this with @brentzundel 's suggestions.

2020-10-12 14:43 UTC, msporny commented
@rhiaro waiting on you to merge @brentzundel's changes to make sure you're ok with them.

2020-10-19 01:34 UTC, kdenhartog approved these changes
Looks like @brentzundel suggestions have been merged now as well

2020-10-26 14:05 UTC, msporny commented on index.html
> +model described in this specification and complies with with the relevant
Merged.

2020-10-26 14:05 UTC, msporny commented on index.html
> +in Section <a href="#identifier"></a> and complies with relevant normative
Merged.

2020-10-26 14:05 UTC, msporny approved these changes

2020-10-26 14:05 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2020-10-26 14:05 UTC, merged