Add concrete serialization rules for JSON based on new data types section.
w3c/did-core pull request #469
Opened 2020-11-24 16:29 UTC by msporny

This PR builds on top of #455 by adding concrete JSON serialization/deserialization rules for production and consumption. If this PR is acceptable the the group, similar PRs will be raised for the JSON-LD and CBOR sections.

2020-11-24 20:27 UTC, jricher requested changes
Mostly good, but needs to be more pedantic to cover corner cases and things like unknown properties in a deterministic way. Changes suggested should not change the intent of the text but make it more strongly defined.

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="RFC8259#section-4">JSON Object</a>
Enumerate the mapping more explicitly:

```suggestion
<a data-cite="RFC8259#section-4">JSON Object</a>, each property is represented as a member of the JSON Object with the property name as the member name and the property value according to its type, as defined in this section
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="RFC8259#section-5">JSON Array</a>
```suggestion
<a data-cite="RFC8259#section-5">JSON Array</a>, each element of the list is added, in order, as a value of the array according to its type, as defined in this section
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="RFC8259#section-5">JSON Array</a>
```suggestion
<a data-cite="RFC8259#section-5">JSON Array</a>, each element of the list is added, in order, as a value of the array according to its type, as defined in this section
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="INFRA#maps">ordered&nbsp;map</a>
```suggestion
<a data-cite="INFRA#maps">ordered&nbsp;map</a>, each member of the JSON Object is added as a property to the ordered map with the property name being the member name and the value converted based on the JSON type and, if available, property definition, as defined here; as no order is specified by JSON Objects, no insertion order is guaranteed
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="INFRA#list">list</a>
```suggestion
<a data-cite="INFRA#list">list</a>, each value of the JSON Array is added to the list in order, converted based on the JSON type of the array value, as defined here
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="INFRA#ordered-set">ordered&nbsp;set</a>
```suggestion
<a data-cite="INFRA#ordered-set">ordered&nbsp;set</a>, each value of the JSON Array is added to the ordered set in order, converted based on the JSON type of the array value, as defined here
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="RFC8259#section-7">JSON String</a>
```suggestion
<a data-cite="RFC8259#section-7">JSON String</a>, where data model property value type is <a>string</a> or unknown
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +is a <a data-cite="INFRA#list">list</a>
```suggestion
<a data-cite="RFC8259#section-5">JSON Array</a> where data model property value
is a <a data-cite="INFRA#list">list</a> or unknown
```

2020-11-24 20:27 UTC, jricher commented on index.html
> +<a data-cite="RFC8259#section-6">JSON Number</a> with a fractional component
```suggestion
<a data-cite="RFC8259#section-6">JSON Number</a> with a fractional component, or when property value is a <a>double</a> regardless of inclusion of fractional component
```

2020-11-24 22:22 UTC, msporny commented
> needs to be more pedantic to cover corner cases and things like unknown properties in a deterministic way.

Merged all of your suggestions, @jricher.

2020-11-24 23:21 UTC, kdenhartog approved these changes
Descriptions look good and precise. LGTM

2020-11-25 12:16 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-11-24-did#section4) on 2020-11-24)

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 4. serialization rules 

_See github pull request [#469](https://github.com/w3c/did-core/pull/469)._




**Manu Sporny:** too note the new PRs 469, needs review  
… this is regarding concrete serialization rules  
… daniel buchner raised another PR regarding equivalence properties  
… please review PRs  

_See github pull request [#431](https://github.com/w3c/did-core/pull/431)._




</details>

2020-11-25 12:16 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-11-24-did#section5) on 2020-11-24)

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 5. other PRs need review

**Brent Zundel:** lots of PRs need review, moving on...  

_See github pull request [#469](https://github.com/w3c/did-core/pull/469)._




**Justin Richer:** regarding 469 and follow ons, it is overly pedantic, but it needs to be... and also when considering other representations... it needs to be really spelled out here.  

> *Justin Richer:* engineers are the worst runtime environment possible....

**Jonathan Holt:** regarding the cbor section, i like it being pedantic, still struggling with the number types  
… hard to map CBOR to the ADM without number types in the ADM  

**Manu Sporny:** we have a number in the ADM, and they should map to CBOR  

**Jonathan Holt:** double is not specific enough... these types are not precise enough for double vs float.  

**Brent Zundel:** next topic, moving forward plan.  

</details>

2020-11-28 18:04 UTC, dlongley approved these changes

2020-11-30 14:54 UTC, OR13 approved these changes

2020-12-01 15:23 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2020-12-01 15:23 UTC, merged