Align CBOR production/consumption rules with rest of specification.
w3c/did-core pull request #476
Opened 2020-12-06 23:07 UTC by msporny

2020-12-08 16:27 UTC, jonnycrunch commented on index.html
> +        <table class="simple" id="vanilla-cbor-representation-production">
Vanilla CBOR might not be the best characterization.

2020-12-09 20:33 UTC, brentzundel approved these changes

2020-12-11 14:40 UTC, OR13 commented on index.html
> +        <table class="simple" id="vanilla-cbor-representation-production">
```suggestion
        <table class="simple" id="cbor-representation-production">
```

2020-12-11 14:40 UTC, OR13 requested changes
prefer for us to finish describing "cbor" well before attempting to add subclasses of cbor to the spec

2020-12-11 17:31 UTC, jonnycrunch commented on index.html
> +        <table class="simple" id="vanilla-cbor-representation-production">
Agree with @OR13 !

2020-12-12 18:46 UTC, msporny commented
> prefer for us to finish describing "cbor" well before attempting to add subclasses of cbor to the spec

Noting the "request changes" -- can I raise that in another PR? I assume this means you'd rather /not/ see the CBOR Extensions and DagCBOR stuff in the spec until we get the basics of CBOR hammered down, @OR13?

2020-12-13 20:37 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2020-12-13 20:37 UTC, merged