Added tables to replace the introductory part on core properties - bis for github
w3c/did-core pull request #536
Opened 2021-01-11 11:02 UTC by iherman

resolving merge conflicts in #528 would have been terrible; git's rebase went completely crazy. However, my changes in #528 were fully concentrated to the initial part of §5, so I decided to make a fresh branch and manually transfer my changes instead.

@rhiaro, would you mind checking that the changes here are indeed the same as the changes proposed in #528 (except that they are on the fresh branch)? If so, @msporny, I believe the comments in #528 stand for this one, and this PR could be merged (and #528 simply closed).

2021-01-11 12:29 UTC, rhiaro requested changes
I've said it before, but this arrangement of the core properties is so much better and easier to read!

My one query is - do Verification Methods need to be referred to by DIDs (as stated here - but not in current spec text) or can they be any URIs?

And the caveat that once this is merged I will clean up the rest of the prose in the section so normative statements aren't duplicated. I also think we should use `<dfn>` tags around the properties in the table, but that can come alongside the prose cleanup.

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +              <td>A <a data-cite="INFRA#maps">map</a> representing a JSON Web Key that conforms to [[RFC7517]].</td>
```suggestion
              <td>A <a data-cite="INFRA#maps">map</a> representing a JSON Web Key that conforms to [[RFC7517]]. This value MUST NOT contain "d", or any other members of the private information class as described in <a href="https://tools.ietf.org/html/rfc7517#section-8.1.1">Registration Template</a>.</td>
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> or <a data-cite="INFRA#string">strings</a> that conf
```suggestion
                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> (see <a href="#core-properties-for-a-verification-method"></a>) or <a data-cite="INFRA#string">strings</a> that conform to the rules of [[RFC3986]] for <a>URIs</a>. <br/>The <a>URI</a> values SHOULD also conform to the rules in Section <a href="#did-url-syntax"></a>.
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> or <a data-cite="INFRA#string">strings</a> that conf
```suggestion
                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> (see <a href="#core-properties-for-a-verification-method"></a>) or <a data-cite="INFRA#string">strings</a> that conform to the rules of [[RFC3986]] for <a>URIs</a>. <br/>The <a>URI</a> values SHOULD also conform to the rules in Section <a href="#did-url-syntax"></a>.
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> ins<a data-cite="INFRA#ordered-map">maps</a>ances or <a data-cite="INFRA#string">strings</a> t
```suggestion
                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> (see <a href="#core-properties-for-a-verification-method"></a>) or <a data-cite="INFRA#string">strings</a> that conform to the rules of [[RFC3986]] for <a>URIs</a>. <br/>The <a>URI</a> values SHOULD also conform to the rules in Section <a href="#did-url-syntax"></a>.
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> or <a data-cite="INFRA#string">strings</a> that conf
```suggestion
                An <a data-cite="INFRA#ordered-set">ordered set</a> of either <a>Verification Method</a> <a data-cite="INFRA#ordered-map">maps</a> (see <a href="#core-properties-for-a-verification-method"></a>) or <a data-cite="INFRA#string">strings</a> that conform to the rules of [[RFC3986]] for <a>URIs</a>. <br/>The <a>URI</a> values SHOULD also conform to the rules in Section <a href="#did-url-syntax"></a>.
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +              <td>An <a data-cite="INFRA#ordered-set">ordered set</a> of <a>Service Endpoint</a> <a data-cite="INFRA#ordered-map">maps</a>.</td>
```suggestion
              <td>An <a data-cite="INFRA#ordered-set">ordered set</a> of <a>Service Endpoint</a> <a data-cite="INFRA#ordered-map">maps</a> (see <a href="#core-properties-for-a-service-endpoint"></a>).</td>
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                A <a data-cite="INFRA#string">string</a> that conforms to the rules of [[RFC3986]] for <a>URI</a>-s and which SHOULD also conform to the rules in Section <a href="#did-url-syntax"></a
```suggestion
                A <a data-cite="INFRA#string">string</a> that conforms to the rules of [[RFC3986]] for <a>URIs</a> and which SHOULD also conform to the rules in Section <a href="#did-url-syntax"></a>.
```

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                when used on a <a>Service Endpoint</a>: a <a data-cite="INFRA#string">string</a> that conforms to the rules of [[RFC3986]] for <a>URI</a>-s.
```suggestion
                a <a data-cite="INFRA#string">string</a> that conforms to the rules of [[RFC3986]] for <a>URIs</a>.
```

I think the "when used on a service endpoint" part is implicit by the table

2021-01-11 12:29 UTC, rhiaro commented on index.html
> +                A <a data-cite="INFRA#string">string</a> that conform to the rules of [[RFC3986]] for <a>URI</a>-s, a <a data-cite="INFRA#string">map</a>, or an <a data-cite="INFRA#ordered-set">order
```suggestion
                A <a data-cite="INFRA#string">string</a> that conform to the rules of [[RFC3986]] for <a>URIs</a>, a <a data-cite="INFRA#string">map</a>, or an <a data-cite="INFRA#ordered-set">ordered set</a> composed of a one or more <a data-cite="INFRA#string">strings</a> that conform to the rules of [[RFC3986]] for <a>URIs</a> and/or <a data-cite="INFRA#string">maps</a>.
```

2021-01-11 13:39 UTC, iherman commented
@rhiaro thanks for the editorial comments; I have taken care of them.

As for

> My one query is - do Verification Methods need to be referred to by DIDs (as stated here - but not in current spec text) or can they be any URIs?

yes, I was wondering about that myself. _All_ examples in the text use DID URL-s for the various verifications methods but the spec is silent on this aspect altogether. This is one of the places when the reader might be influenced by the examples.

I have put a _SHOULD_ for a DID URL to reflect the examples. If that is incorrect, then at least one examples, if not several, should use a different URI to make the point. Personally, I can live with either way.

2021-01-11 13:45 UTC, iherman commented
(In case I was not clear: https://github.com/w3c/did-core/pull/536/commits/41af738c47a4f612f61a9c2388bea1fc45249175 covers the editorial changes.)

2021-01-11 21:23 UTC, rhiaro commented
> I have put a SHOULD for a DID URL to reflect the examples.

I checked with @msporny about this earlier, and I think the SHOULD here is correct.

2021-01-14 10:17 UTC, iherman commented
@msporny can we/you merge this PR (and close #528)?

2021-01-14 10:33 UTC, rhiaro approved these changes

2021-01-17 18:18 UTC, msporny approved these changes

2021-01-17 18:19 UTC, msporny commented
Editorial, multiple reviews here and in #528, changes requested and made, no objections, merging.

2021-01-17 18:21 UTC, merged