Change DID parameter names to camelCase.
w3c/did-core pull request #553
Opened 2021-01-18 10:21 UTC by peacekeeper

In https://github.com/w3c/did-core/pull/533, metadata property names were changed from using hyphens to camelCase (e.g. `content-type` -> `contentType`). That same PR also changed both the `version-id` metadata property and the `version-id` DID parameter to `versionId`.

This PR here changes the remaining two concerned DID parameters `relative-ref` and `version-id` to be consistent with the others.

2021-01-18 23:25 UTC, brentzundel approved these changes

2021-01-20 03:40 UTC, kdenhartog approved these changes

2021-01-20 14:29 UTC, OR13 commented
I find pascal case harder to read, and therefore a poor choice for URIs.... what we are doing is establishing a convention here. I am fine with pascal case is the convention... I would prefer some explanation for why we are encouraging this, over just making the change... future readers will have questions.

2021-01-20 14:30 UTC, OR13 requested changes
I would prefer to see a `note` or `advisement` regarding this change, and noting that it is a convention, not a requirement.

2021-01-20 17:24 UTC, peacekeeper commented
> I am fine with pascal case as the convention

@OR13 "pascal case" I think would be "RelativeRef" or "VersionId"? I don't think anyone has ever suggested or even mentioned that... Are you proposing we switch to that?

2021-01-24 18:07 UTC, msporny approved these changes

2021-01-25 15:54 UTC, OR13 commented
yes, sorry, I always confuse PascalCase, TitleCase and camelCase.

2021-01-26 15:01 UTC, merged