Moves deterministic encoded CBOR language back to CBOR section
w3c/did-core pull request #586
Opened 2021-01-28 17:12 UTC by jonnycrunch

This PR undoes the `editorial` changes to get us back on having the discussion regarding Deterministically Encoded CBOR back to the conversations.  

The language builds on the updated CBOR spec [RFC #8949](https://tools.ietf.org/html/rfc8949#section-4.2)

2021-01-28 17:15 UTC, TallTed commented on index.html
> +
typos and line lengths
```suggestion
To produce a deterministic canonical CBOR representation of a DID
document and facilitate maximal lossless compatibility with other core
representations via the Abstract Data Model the following constraints
of a CBOR representation of a DID Document model MUST be followed:
        </p>
```

2021-01-28 17:18 UTC, TallTed commented on index.html
> +            <li>The keys in every map must be sorted lowest value to highest. Sorting is performed on the bytes of the representation of the keys. If two keys have different lengths, the shorter one
```suggestion
            <li>
Property names MUST be represented as text string (major type 3) and
contain only UTF-8 strings.
            </li>
            <li>
Undefined Values of Required Properties as defined in <a
href="#data-model">the Data Model</a> that are absent from the CBOR
representation SHOULD be labeled with Primitive type (major type 7)
with value 23 (Undefined value).
            </li>
            <li>
Property names in each CBOR map MUST be unique.
            </li>
            <li>
Integer encoding MUST be as short as possible.
            </li>
            <li>
The expression of lengths in CBOR major types 2 through 5 MUST be as
short as possible.
            </li>
            <li>
The keys in every map must be sorted lowest value to highest. Sorting
is performed on the bytes of the representation of the keys. If two
keys have different lengths, the shorter one sorts earlier.  If two
keys have the same length, the one with the lower value in (byte-wise)
lexical order sorts earlier.
            </li>
```
line lengths

2021-01-28 19:01 UTC, iherman commented
@jonnycrunch did you use a different github persona than the one you registered with the WG? Otherwise I don't know why this PR wasn't accepted.

I will set this as editorial, which will release the lock, but you should check, please. Thx

2021-01-31 21:35 UTC, msporny commented
@jonnycrunch, I'm confused by this PR. The text was already moved back in this commit: https://github.com/w3c/did-core/commit/5b7c489e3231a3e31171c7f40c71973c197a612f which was announced to the WG here: https://lists.w3.org/Archives/Member/member-did-wg/2021Jan/0002.html

Is there some difference between the text in the spec and what you're proposing in the PR?

2021-02-01 17:39 UTC, brentzundel commented
@jonnycrunch I believe the changes you are recommending here have already been made.

2021-02-02 23:19 UTC, OR13 requested changes
make no mention on canonical, based on the comments from the call... prefer to not see that language / think this should be closed.

2021-02-03 05:10 UTC, msporny commented
@brentzundel wrote:
> @jonnycrunch I believe the changes you are recommending here have already been made.

I checked a few days ago and checked again today per @jricher's request -- the changes in this PR were merged into the specification before this PR was raised. There are wording differences due to a refactoring of language that @peacekeeper applied to the spec wrt. ADM entry keys, etc. This PR undoes some of those changes. The group also discussed this PR during the special topic call today and decided to close it.

For those reasons, this PR is marked pending close and will be closed in 7 days or when @jonnycrunch confirms that we can close this PR, whichever event happens sooner.

2021-02-10 17:14 UTC, msporny commented
> This PR is marked pending close and will be closed in 7 days or when @jonnycrunch confirms that we can close this PR, whichever event happens sooner.

7 days have elapsed, closing.

2021-02-10 17:14 UTC, closed without merging