Make DID Resolution section concrete and testable.
w3c/did-core pull request #587
Opened 2021-02-01 04:37 UTC by msporny

This PR is intended to address issue #549 by converting the abstract functions discussed in the DID Resolution and DID URL Dereferencing sections into concrete, testable functions. The PR uses a very light amount of WebIDL while keeping much of what we had the same as before. It also tries to strike a balance by enabling at least one concrete realization of the interface without preventing other concrete interfaces from being realized.

2021-02-01 09:12 UTC, peacekeeper commented
The idea behind the abstract functions was to make it crystal clear that DID resolution is not a single protocol (as in DNS), but that invocation of the resolution function can come in many forms (command line, SDK call, HTTP API, DIDComm, ...). I think your PR still allows this by saying _"DID resolver implementations realize at least the following interface (or one that is functionally equivalent)"_.

However I don't really understand how adding one concrete form (WebIDL) makes the section more testable? I thought WebIDL is intended for browser APIs, is anyone working on DID resolution in browsers?

The biggest change seems to be that it removes `resolveRepresentation` (and at the same time changes `resolve` to be like `resolveRepresentation`). I don't think this is a good idea, we had many meetings/issues/PRs that led to this design. DID resolution can happen without ever dealing with any concrete representation.

Some smaller comments
- I like the reformatting efforts, including camelCase and cleaning up section headings and property names
- I could live with the rename from "did-resolution-input-metadata" to "resolutionOptions" is okay, but would slightly prefer to continue using the term "metadata" also for inputs, to point out that input metadata and output metadata follow the same data model (similar to HTTP request/response headers).

2021-02-01 10:00 UTC, iherman requested changes
We should **_NOT_** use WebIDL. We would get into a long, pointless, and religious debate on what WebIDL is for, whether it is a formalism that can be used outside of browsers or not, whether the inclusion of WebIDL in the standard means that browsers are required to implement it or not.

The JSON-LD 1.1 Recommendation vote was delayed exactly on those grounds: there were formal objections from some AC members to publish the Recommendation. We did find some sort of compromise WebIDL syntax solution at the end, but it was not pleasant. We would incur the danger of finding ourselves in the same discussions. It is not worth it.

2021-02-01 16:00 UTC, OR13 commented
> The biggest change seems to be that it removes `resolveRepresentation` (and at the same time changes `resolve` to be like `resolveRepresentation`). I don't think this is a good idea, we had many meetings/issues/PRs that led to this design. DID resolution can happen without ever dealing with any concrete representation.

agree with @peacekeeper ... there was specific language about changing the function signature... however, I think its better to have 1 concrete function signature than 2 abstract ones... so I am supportive of the change.

I have always been confused by how resolve is different from resolve representation, here is how we implemented it:

https://github.com/transmute-industries/did-key.js/blob/master/packages/did-key-common/src/getResolver.ts#L90

We build a resolver of did key, from its Key Pair class.. ad we only support "resolveRepresentation" but we call it "resolve".

2021-02-01 16:28 UTC, msporny commented
> The JSON-LD 1.1 Recommendation vote was delayed exactly on those grounds: there were formal objections from some AC members to publish the Recommendation. 

I'll note that the JSON-LD API specification /did/ end up using WebIDL: https://www.w3.org/TR/json-ld-api/#the-jsonldprocessor-interface

I can remove the letters "WebIDL"... but the result is going to effectively be WebIDL. If folks feel like removing those letters from the specification is going to make CR/PR easier, then that's fine, I can do it. It is a bit ridiculous of a few AC Members to object -- on what grounds did they object?

Keep in mind that I tried to say: "This is one way to do it, it's not the only way" to prevent these sorts of objections. We're effectively saying... "if you're implementing in Javascript, here's a concrete way to do it... but it's not the only way, you can do this same sort of thing as an HTTP API, a gRPC API, or anything else."

2021-02-01 16:31 UTC, msporny commented
> I think your PR still allows this by saying _"DID resolver implementations realize at least the following interface (or one that is functionally equivalent)"_.

Yes, exactly... that's the intent. "This is just one concrete way to realize resolution/dereferencing, but there are other ways and those are fine too as long as they're functionally equivalent."

> However I don't really understand how adding one concrete form (WebIDL) makes the section more testable? I thought WebIDL is intended for browser APIs, is anyone implementing a DID resolution browser API?

WebIDL is meant for Javascript APIs, and yes, there are multiple companies implementing resolvers using Javascript. It doesn't mean that's the /only/ way you can have a conformant DID resolver implementation... it just says that that is /one/ path to conformance that's testable.

> The biggest change seems to be that it removes `resolveRepresentation` (and at the same time changes `resolve` to be like `resolveRepresentation`). I don't think this is a good idea, we had many meetings/issues/PRs that led to this design. DID resolution can happen without ever dealing with any concrete representation.

If there is no concrete representation, there is nothing to test. That's the point -- we can't deal in the abstract when we go to write the test suite tests.

2021-02-01 16:33 UTC, iherman commented
> 
> I can remove the letters "WebIDL"... but the result is going to effectively be WebIDL. If folks feel like removing those letters from the specification is going to make CR/PR easier, then that's fine, I can do it. It is a bit ridiculous of a few AC Members to object -- on what grounds did they object?

That, by using WebIDL, we say that the feature must (also) be implemented in a browser. Do we want to get to that discussion?

> 
> Keep in mind that I tried to say: "This is one way to do it, it's not the only way" to prevent these sorts of objections. We're effectively saying... "if you're implementing in Javascript, here's a concrete way to do it... but it's not the only way, you can do this same sort of thing as an HTTP API, a gRPC API, or anything else."

Believe me, I understand. One way to do this, maybe, is to move the WebIDL part into an (explicitly non-normative!) appendix in the spec to avoid unnecessary time spent on this later.

2021-02-01 17:30 UTC, peacekeeper commented
All the sources I find about WebIDL say that it's for implementation in web browsers, not for generic JavaScript APIs.

And even if it was, I don't understand how this makes the section more testable? What about non-JavaScript implementations of DID Resolution, how would they benefit from the switch to WebIDL, and how would they be tested?

2021-02-01 19:49 UTC, msporny commented
@iherman wrote:
> That, by using WebIDL, we say that the feature must (also) be implemented in a browser. Do we want to get to that discussion?

... but that objection is ridiculous! :P That's not only what WebIDL is for... sure, we want to avoid ridiculous objections... but the JSON-LD API is an example that those ridiculous objections are often stayed and more sensible folks are allowed to proceed.

@peacekeeper wrote:
> All the sources I find about WebIDL say that it's for implementation in web browsers, not for generic JavaScript APIs.

The specification for WebIDL defines what WebIDL is for -- it's for ECMAScript (aka: JavaScript):

https://heycam.github.io/webidl/#introduction

> And even if it was, I don't understand how this makes the section more testable? 

Because at least a JavaScript developer can take a WebIDL interface and write code against it. What we had in the specification before could be misinterpreted in a variety of different ways. Can I use a dictionary? A map? A Map (which is not a map)? Can I expose this over an HTTP interface? The answer to all those questions is "yes" -- and that's a good indication that the thing isn't easily testable and if we were to write tests, people would disagree with the tests because they interpreted the language incorrectly.

> What about non-JavaScript implementations of DID Resolution, how would they benefit from the switch to WebIDL, and how would they be tested?

I have no idea how we'd test those things... and that's the problem... it was not clear how any of this would be tested because the interface that we'd have to use was purely abstract. It's like asking people to test the DID specification using purely the Abstract Data Model without resorting to using a representation. You can't test things that are abstract because they are... abstract! :yum:

2021-02-01 20:39 UTC, msporny commented
@iherman and @peacekeeper -- trying to figure out how to change this PR so it would address each of your concerns. If I were to remove the "WebIDL" text and replace it with "an example function signature in JavaScript" as a non-normative example... would that address both of your concerns?

2021-02-01 20:58 UTC, jricher requested changes
This is not a simple swap out of one description language for another.

This change set removes the `resolveRepresentation` function and collapsed a number of previously separated bits of functionality into a single catch all-function, effectively undoing months of work and consensus within the working group.

This PR should be rejected.

2021-02-01 21:07 UTC, msporny commented
@jricher wrote:
> This change set removes the resolveRepresentation function and collapsed a number of previously separated bits of functionality into a single catch all-function, effectively undoing months of work and consensus within the working group.

It only thing that was removed was the purely abstract part that was not testable. It would be fairly trivial to add that one abstract function back in if that would remove your objection. The core of the spec changes for this PR took about an hour to make, which demonstrates that there really weren't a ton of functional changes (most of the work was editorial reformatting changes -- renaming variables, changing deeply nested sections into definition lists that match the rest of the specification, etc).

The biggest change was renaming resolveRepresentation -> resolve and the WebIDL rework. What other changes do you think happened?

2021-02-01 21:41 UTC, OR13 approved these changes

2021-02-01 21:44 UTC, OR13 commented
I like the web idl definitions, and the fact that the awkward double resolution definition is gone, I think this PR is a step in the right direction.

I could live without the WebIDL and instead see the function defined in INFRA, for the sake of consistency that might be a better path to take.

2021-02-02 05:26 UTC, iherman commented
> @iherman and @peacekeeper -- trying to figure out how to change this PR so it would address each of your concerns. If I were to remove the "WebIDL" text and replace it with "an example function signature in JavaScript" as a non-normative example... would that address both of your concerns?

Yes, that could work. Actually, I would probably prefer TypeScript to JavaScript, because we can then provide type annotations/definitions in the interface. Typescript is close enough to JavaScript that vanilla JavaScript users would also understand it.

2021-02-02 06:49 UTC, peacekeeper commented
> > And even if it was, I don't understand how this makes the section more testable?
> 
> Because at least a JavaScript developer can take a WebIDL interface and write code against it. What we had in the specification before could be misinterpreted in a variety of different ways. Can I use a dictionary? A map?

@msporny I still don't get it. The functions currently specify inputs and outputs. Those inputs and outputs are well-defined using INFRA. I'm perfectly able to write code that takes the inputs and returns the outputs of those functions, and I don't really need any extra spec text for that.

Is there an "official INFRA way" to define functions? That might be ideal.

> If I were to remove the "WebIDL" text and replace it with "an example function signature in JavaScript" as a non-normative example... would that address both of your concerns?

I'd be fine with leaving the functions as-is and adding a JavaScript/TypeScript example. In this case I would suggest also adding the [HTTP(S) binding](https://w3c-ccg.github.io/did-resolution/#bindings-https) from the DID Resolution spec as a second concrete example of how those functions can be implemented, even if that can only be a non-normative reference of course.

2021-02-02 06:59 UTC, peacekeeper commented
> This change set removes the `resolveRepresentation` function and collapsed a number of previously separated bits of functionality into a single catch all-function, effectively undoing months of work and consensus within the working group.

I agree with @jricher. Personally, I would also prefer a single function rather than two. I raised several PRs myself which tried to do it with a single function, but they were all rejected, and the WG then arrived at the current design.

For further information, see the following 13 (!) PRs related to this topic with >200 comments and links to multiple special topic calls:

https://github.com/w3c/did-core/pulls?q=is%3Apr+label%3Acontract+

2021-02-02 15:55 UTC, msporny commented
@peacekeeper @iherman, I have put forward an alternate PR that removes all WebIDL and uses a Typescript interface definition as an example, does that work for both of you? You can review the changes in PR #591.

2021-02-02 16:07 UTC, peacekeeper commented
> "Now that we know that removing the abstract resolve() function doesn't impact implementations, do we still want to keep it, if so, why?"

I don't think we know that. There are implementations that implement resolve(), i.e. they take a DID as input and return a DID document data model that is not in any concrete representation.

2021-02-02 23:13 UTC, OR13 commented
> > "Now that we know that removing the abstract resolve() function doesn't impact implementations, do we still want to keep it, if so, why?"
> 
> I don't think we know that. There are implementations that implement `resolve()`, i.e. they take a DID as input and return a DID document data model that is not in any concrete representation.

ahh... that is not a thing we do anywhere... but maybe there are folks that are returning Class or Objects that represent a DID Document in the ADM... in which case this would impact those...

2021-02-02 23:21 UTC, OR13 commented on index.html
> +        <pre class="idl">
sad web idl

2021-02-03 04:40 UTC, msporny commented
Closing in favor of PR #592.

2021-02-03 04:40 UTC, closed without merging