Add diagram "production and consumption".
w3c/did-core pull request #596
Opened 2021-02-03 11:53 UTC by peacekeeper

For the "Representations" section:

_Diagram illustrating how representations of the data model are produced and consumed, including in JSON, JSON-LD, and CBOR._

![diagram-production-consumption](https://user-images.githubusercontent.com/290941/106743353-916fb000-661e-11eb-855f-bdcbd36ae641.png)

2021-02-03 21:50 UTC, TallTed commented
As with https://github.com/w3c/did-core/pull/595#issuecomment-772845778...

Needs much more detailed `longdesc` description

2021-02-05 22:34 UTC, OR13 requested changes
I would prefer to see the abstract data model represented some other way.

I also don't understand how the JSON-LD representation produced can be produced from the ADM that does no contain its entries... for example, when serializing a DID Document with extensions for PGP...

The abstract data model would need to contain the `@context` for the registered extensions, such as:

https://or13.github.io/lds-pgp2021/#did-document

Your example is misleading, since it assumes that did core context can be injected into the JSON serialization of the ADM to produce JSON-LD... when in fact that is not acceptable.... see my counter example:

```
{
  "@context": ["https://www.w3.org/ns/did/v1", "https://w3id.org/pgp/v1"],
  "id": "did:example:123",
  "assertionMethod": [
    {
      "id": "did:example:123#test-id",
      "type": "PgpVerificationKey2021",
      "controller": "did:example:123",
      "publicKeyPgp": "-----BEGIN PGP PUBLIC KEY BLOCK...."
    }
  ]
}
```

It is true that INFRA has all that the ADM needs to represent `did+json` / `did+ld+json`... it is false that you can just include an `@context` and get a valid JSON-LD representation, see above.

In order to account for this, here are a couple proposals:

1. don't show the infra map (since the ADM is abstract, showing anything here might be misleading)
2. show infra and include the context, with or without registered extensions, this would make the JSON-LD example make sense.
3. remove the JSON-LD representation and just show ADM to JSON.



See ![https://user-images.githubusercontent.com/290941/106743345-8b79cf00-661e-11eb-851d-56154cf0dee7.png](https://user-images.githubusercontent.com/290941/106743345-8b79cf00-661e-11eb-851d-56154cf0dee7.png)

2021-02-07 18:45 UTC, rhiaro commented
Agreed with @OR13 .. there are terms in the JSON-LD representation which are not in the context, making this representation invalid, per:

> Producers SHOULD NOT produce DID documents that contain properties not defined via the @context.

And also need to improve a11y, for #118

2021-02-08 00:12 UTC, peacekeeper commented
@rhiaro thanks, I agree. I just pushed an update that fixes this, and the JSON-LD representation should now be valid. Do you agree?

![diagram-production-consumption](https://user-images.githubusercontent.com/290941/107163582-916b0980-69aa-11eb-87eb-38878398f24b.png)

2021-02-08 15:50 UTC, OR13 commented
This diagram remains incorrect:

https://github.com/w3c/did-core/pull/596#issuecomment-774794739

I will not approve this PR until:

`@context` is included in the DID Document INFRA map that is used to produce the JSON-LD.... 

Alternative solutions:

1. split the diagram up, so that did+json and did+cbor are produced from an ADM that does not have an `@context` but did+ld+json is produced from an ADM that contains an `@context`.
2. include `@context` in the ADM, but not in the JSON or CBOR representations
3. remove the incorrect diagram regarding JSON-LD production.

2021-02-08 16:49 UTC, iherman commented
@OR13 

> ... for example, when serializing a DID Document with extensions for PGP...
> 
> The abstract data model would need to contain the `@context` for the registered extensions, such as:
> 
> https://or13.github.io/lds-pgp2021/#did-document
> 

Hm. If I am overly pedantic, then I do not agree...

In my view, the ADM does _not_ include the context. The ADM representations for that particular DID includes a term  (`PgpVerificationKey2021`) that is not defined as a bona fide core DID term. The ADM "processor" (method, whatever) must then consult the registry, locate the `PgpVerificationKey2021` entry in the registry, find the corresponding context reference, and must add that `@context` to the generated JSON-LD. This does _not_ mean that the context, per se, is part of the data model, it means that there is a well-defined course of action for a processor to handle the non-core terms which involves the registry and the generation of additional `@context` statements. That is very different. (Whether the processor does this registry look up on the fly, or whether it has a cached version, becomes an implementation detail from the point of view of the DID Core spec.)

This process is not really described in the spec (and it probably should not, this should probably be the subject of the final version of the method specification when it comes). Maybe the spec should at least hint at this (oops, we have one more day to add a PR if we want to have that...:-) 

I may agree that something about this may have to be part of the diagram but I am not sure: the diagram may become very bloated.

You may try to convince me not to be that pedantic:-)

2021-02-08 19:10 UTC, OR13 commented
@iherman https://w3c.github.io/did-core/#production-0

See the current normative requirements for JSON-LD production.

Its not possible to produce `application/did+ld+json` for a "DID Document: INFRA<MAP>" without it containing an `@context`... I'm sorry this is confusing, but is pretty fundamental to agreeing to the ADM... without my assertion being true, we don't have an ADM representation fo JSON-LD, and we don't have consensus on the ADM at all... I recally making this point a number of times on WG calls, and my understanding of consensus has been captured in markus's image here:

![https://user-images.githubusercontent.com/290941/106743345-8b79cf00-661e-11eb-851d-56154cf0dee7.png](https://user-images.githubusercontent.com/290941/106743345-8b79cf00-661e-11eb-851d-56154cf0dee7.png)

2021-02-09 21:42 UTC, msporny requested changes
@iherman wrote:
>  The ADM "processor" (method, whatever) must then consult the registry, locate the PgpVerificationKey2021 entry in the registry, find the corresponding context reference, and must add that @context to the generated JSON-LD. 

Uh oh, we discussed this to death and came to the conclusion that the above is absolutely not true -- because you won't know how to order contexts using the algorithm described above... `@context` is preserved in the ADM, full stop, I believe we had settled that long ago.

I agree with @OR13 -- the diagram is incorrect and needs to be fixed.

2021-02-09 22:25 UTC, peacekeeper commented
@jricher and @iherman are correct, the ADM does NOT need to contain `@context` or other representation-specific entries. I believe @OR13 's and @msporny 's characterization of the conclusion of the ADM discussions is inaccurate.

What we agreed on was that unknown entries including representation-specific ones such as `@context` can be preserved in the ADM, e.g. when you first consume JSON-LD and then produce JSON, then you will still have the `@context`. Personally I still believe this is a big mistake, but that was the agreement. This is why my diagram in https://github.com/w3c/did-core/pull/595 shows `@context` as a representation-specific entry in the ADM.

However, this does NOT mean that `@context` MUST be present in the ADM when you construct an instance of the DID document data model from scratch (or obtain one as a result of the `resolve()` function), and then want to produce a JSON-LD representation from it.

I'm very surprised to hear that this is being proposed now.

If that's your position, then you are suggesting

1. Either that at the time when you construct an instance of the data model, you must already anticipate which representations (current and future) you may possibly want to produce from the data model later.
2. Or, even worse, that you need to populate the ADM differently for each representation (this is what @OR13 seems to propose in https://github.com/w3c/did-core/pull/596#issuecomment-775245040).

Both approach would render the concept of an "abstract" data model absurd. Both are likely to break as soon as another representation such as XML or YAML is added.

2021-02-10 15:27 UTC, OR13 commented
As you can see in https://github.com/w3c/did-core/pull/610 there is clearly a misunderstanding regarding JSON-LD DID Document Production and Consumption.

The problem is compounded by diagrams that appear to look like JSON....

It is true that an `@context` might be internally represented differently than INFRA when the document is constructed from scratch.... it is FALSE that the the ADM will represent the `@context` as something other than an INFRA when it consumes a serialized JSON-LD Document.... it is also false that consuming a JSON-LD document somehow "looses the context information"...


In other words... the reason the diagram is wrong is that consuming JSON-LD with and `@context` means it is stored in the ADM (somehow)... full stop.

This makes the diagram false if it contains a consumption arrow for JSON that includes an `@context` or `$schema` and the ADM does not show those values... in the same way that the diagram would be false if it conveyed that properties were dropped as a result of consumption and production.

A separate problem with the diagram is the showing JSON-LD consumption and production require preserving `@context` but the same DID Document being produced and consumed and JSON might not....

This is a function of having 2 representation... and is not solved by pretending that the same information in the ADM can support both... for example.. the diagram implies that somehow JSON->ADM->JSON-LD is possible... but its not... we have proved this... because the ADM cannot know the context for members in JSON..... and no amount of. "I think there is a way" is going to make it into the spec at this point.

So the diagram is confusing / wrong on 2 fronts.

1. consuming a JSON-LD Document is not a lossy process ...`@context` is preserved (somehow).
2. consuming one representation and producing another representation MAY BE a lossy process depending on the representation... for example CBOR integer keys may be lost, other fancy representation specific stuff may not survive the ADM, and some methods will decide that dropping an `@context` is somehow useful (even though its not)

Part of having and ADM means the individual representation features might not be respected in other representations... to mitigate this, we adopted several resolutions regarding consumption and preservation of unregistered properties.

This PR attempts to undo those resolutions with an image that is misleading, and should not be accepted.

2021-02-10 17:28 UTC, msporny commented
> Part of having and ADM means the individual representation features might not be respected in other representations... to mitigate this, we adopted several resolutions regarding consumption and preservation of unregistered properties.

Found the meeting where this was discussed:

https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-11-05-did#section2

@peacekeeper, could you please point out where we agreed to what you're suggesting?

2021-02-10 23:34 UTC, TallTed commented
@OR13 - There are several small but possibly troublesome typos in your last comment; at the least, they cause a hiccup in reading and trying to understand relatively important details. In most (I think, all) of these, `and` has replaced the word which belonged there (mostly if not all `as` or `an`).  I think I figured out what was meant in all cases, but it would be best if you could review and correct the typos in your comment...

2021-02-11 18:15 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-02-11-did-topic#section2) on 2021-02-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 2. production and consumption issue 

_See github pull request [#596](https://github.com/w3c/did-core/pull/596)._




**Manu Sporny:** There are 2 that have raised the question around ADM again  
… markus, would you like to provide a background on both of these PRs and the current concern?  

**Markus Sabadello:** one of these PRs, production and consumption  
… trying to show how production and consumption works and what the relationship is between the data model and the individual representations  
… the data model defined in section 4 and the representations in section 6  
… the data model we define as an infra map  
… not json, not cbor, not xml, it's infra notation  
… the diagram is attempting to show how this abstract data model by going through a production process gets to a concrete representation in json-ld, json and cbor  
… that's it, the discussion and controversial aspect is around whether `@context` is included in the ADM  
… if ADM has to be present in the top left corner in order to produce the json-ld representation  
… that's the discussion  

> *Orie Steele:* its not about production... its about consumption... the consumption arrow is where the error is.

**Markus Sabadello:** I think the consensus after the ADM discussions was the data model, the infra map, can hold `@context`, or other representation specific entries, but it doesn't have to be there  
… this diagram is trying to show the simple case where the data model contains core properties and other representation specific entries they get added in individual representations  

**Orie Steele:** i'm one of the people who doesn't think that this is a simple diagram  
… the consumption arrow is the problem  
… the production arrow is fine  
… how methods choose to represent context internally before production occurs, is up to them  
… context is a representation specific concept  
… consumption rules we have spent time talking about preservation of properties an dthe fact that multiple representations means that unregistered properties are all preserved  
… the arrow violates the WG consensus  
… it sounds like `@context` must be present in the ADM to produce json-ld. I'm not saying that  
… this picture implies somehow you can consume json-ld and lose an `@context`  
… we've admitted we're going to conserve all properties  
… I'll object until we can fix that visualization  
… on markus' original point, `@context` doesn't need to be in the ADM for production  
… but if you're consuming json that contains a member into the ADM and somehow losing it, that is a problem  

**Manu Sporny:** +1 what orie said  
… it's a difficult balance  
… what we're doing here is putting 3 different production/consumption things together  

> *Justin Richer:* for what it's worth, I am in favor of markus_sabadello 's diagrams and do not agree with Orie 's changes.

**Manu Sporny:** because the diagram is trying to show production and consumption across multiple representations we should at least put `@context` in here because in this way, even in consumption in this way, you'd have `@context`  
… the change request is to put `@context` in the ADM  
… it makes it possible for the reader to ask the question why is `@context` disappearing in production here  
… and not here  

> *Orie Steele:* I would not put ``@context`` in the ADM... its confusing... I would split up the diagram

**Manu Sporny:** it could also be that they raise the question fo wait a second you just consumed something where did this `@context` come from?  
… I think there are down sides both ways  
… but the way it is currently proposed makes it seems like `@context` appears out of thin air  
… we can't propose that as how this thing works in general  

**Markus Sabadello:** I made another version of this diagram  
… a subset of the other diagram that doesn't show all the production and consumption at the same time  
… but shows what happens when you consume the json-ld, and `@context` is preserved, and you produce a plain json representation and the `@context` is still there  
… this is the agreement we had after the discussion  
… I still think it's a mistake, but that's what we agreed  

> *Orie Steele:* A series of diagrams seems more helpful

**Markus Sabadello:** I think it's more important to show a diagram that starts with a data model that does not contain any representation specific entries  
… if we put a diagram like this in a prominent space, people would ask why we have something represent specific in an ADM  

> *Ivan Herman:* +1 to markus_sabadello

**Markus Sabadello:** we could have two diagrams  
… one that looks kind of like the one in the PR and in addition something like this  
… that shows preservation of the entries  

**Brent Zundel:** in any simple diagram of a complex system you're going to be making generalizations and making things less precise  
… I think either we clarify with the second diagram that says in this specific case this is what the spec text says  
… or add a sentence that says this diagram is a simplified visualisation and pay attention to spec for specifics  

**Manu Sporny:** +1 to what brent said  
… and +1 to this diagram, I like it much better  
… having a series of diagrams will be easier for people to not get confused over  
… I was going to say in this diagram I'd be fine also with the second thing eliminating `@context`  
… I know that's controversial and some people would disagree  
… it is an issue with round tripping  
… if all of us can look at this diagram and say we're fine with that being in the spec I think we're done  

**Orie Steele:** I think a series of diagrams would help  
… we need the other picture. This picture works for json-ld production and consumption  
… deleting `@context` will work for json production and consumption. Maybe there's a CBOR version to show as well  
… It'd be better to tackle the complex case of what happens if you start with json and you want to produce json-ld in a diagram that's just about that  
… as opposed to a diagram with 6 arrows and hiding what's going on  
… that's confusing  
… as far as manu's proposal for allowing you to produce did+json that drops a property, that violates the consensus of the WG  
… but I'm in favour of a picture of this that's just vanilla json that never has an `@context` in it ever  

**Ivan Herman:** I am sorry but I don't like that one  
… if I am coming from the outside what I see is that the application did+json and did+ld+json are exactly the same  
… if I know a little bit about json-ld then I don't know what the `@context` does and plays what role on the right hand side  
… If I remember well, we separated the representation specific properties form what is in the core set  
… what about making some sort of a diagram which has the data model as it is now  
… without the context  
… and in that box in the upper left, a separate entry somehow for representation specific properties  
… where the context is present  
… we do separate these things  
… context is specifically called out as a special thing in the spec  

> *Shigeya Suzuki:* Isn't it possible to keep representation-specific property as part of didDocumentMetadata ? (I mean, split the upper-left box)...

> *Shigeya Suzuki:* ah, that's what ivan is saying I guess...

**Ivan Herman:** in the representation on the data model there is something else that should be part of the diagram  
… when I produce the json I use it or don't use it  
… and things become clearer  
… but merging the two things for me is a mistake  

**Justin Richer:** +1 to ivan  
… the underlying problem people seem to be having with the original diagram is that the json-ld crowd sees this as okay so obviously you're starting with the thing in the lowe [...]

2021-02-11 21:20 UTC, peacekeeper commented
> the diagram implies that somehow JSON->ADM->JSON-LD is possible... but its not... we have proved this...

It should be possible if the JSON only contains registered properties. If you have a proof that this is not possible, I'd love to see it. Enabling this was the original reason why we introduced the registry (and the requirement to supply a JSON-LD context for each registered property) at the Amsterdam F2F.

If the JSON contains unregistered properties, then I agree this is not possible.

2021-02-15 14:59 UTC, peacekeeper commented
In an attempt to unblock this, @OR13 and @msporny would you agree with this diagram if I change it as follows:

![diagram-production-consumption-production-only](https://user-images.githubusercontent.com/290941/107961860-b8c36700-6fa6-11eb-84bb-07cad14f292a.png)

2021-02-15 15:06 UTC, msporny commented
> In an attempt to unblock this, @OR13 and @msporny would you agree with this diagram if I change it as follows

The diagram is an improvement over the previous one. The diagram is still not clear wrt. where `@context` comes from. I'm trying to add language in the Editorial pass to provide a bucket, expressible via the data model, where you can store/retrieve representation-specific entries during the consumption/production process.

Do you have the diagram above available in an editable format? It would be easier for me to just show you what I'm talking about.

2021-02-16 15:25 UTC, OR13 commented
@peacekeeper I would agree to the diagram in:

https://github.com/w3c/did-core/pull/596#issuecomment-779276110

IF and only IF:

A. `@context` where present in the entries prior to JSON-LD production.
B. `JSON-LD` production was defined as a process that took an `@context` / other representation specific entries.

we cannot create information from nothing...

we probably should have defined functional signatures for production and consumption ages ago....

A. `produce(adm: entries) => Buffer (JSON-LD)`
B. `produce(adm: infraMap, options: infraMap ) => Buffer (JSON-LD)`

I would accept either, B would require significant changes to the spec.

It sounds to me like @peacekeeper might prefer B... in which case production would look like this:

```ts
const produceJsonLd = (entries: object, options: object) =>{
  return JSON.stringify({...entries, ...options.requiredMembers});
}
```

We would be required to define options in did core, and `requiredMembers` infra map... and it would be required to include an `@context` for JSON-LD and a `$schema` for JSON Schema.

2021-02-16 16:01 UTC, peacekeeper commented
> A. `@context` where present in the entries prior to JSON-LD production.

Then how does it magically get removed to produce the plain JSON representation? Anyway, I think adding such requirements won't work, since that would break the concept of an abstract data model.

> Do you have the diagram above available in an editable format?

I'm attaching the source file, yes maybe you can draw your perspective on how it should work..

[production-consumption.zip](https://github.com/w3c/did-core/files/5989879/production-consumption.zip)

2021-02-16 16:08 UTC, OR13 commented
> > A. `@context` where present in the entries prior to JSON-LD production.
> 
> Then how does it magically get removed to produce the plain JSON representation? Anyway, I think adding such requirements won't work, since that would break the concept of an abstract data model.
> 

why would you add an `@context` and then try to produce `application/did+json` ?

...also... `@context` and `$schema` are legal members of JSON.. you can tell because JSON-LD an d JSON Schema are BOTH JSON... you are introducing harmful complexity in an attempt to redefine what JSON is in this WG.

2021-02-23 01:59 UTC, msporny commented
@peacekeeper now that we have the concept of a `representation-specific entries map` can you please update the diagrams to include that (noting that `@context` comes from that map for JSON-LD production). That should allow us to get these diagrams integrated. I will also note that the diagram in the data model section is now wrong (because it contemplates `@context` in the DID Document data model, which is now incorrect).

2021-02-23 08:02 UTC, iherman commented
> I will also note that the diagram in the data model section is now wrong (because it contemplates `@context` in the DID Document data model, which is now incorrect).

Because I have re-created this diagram in draw.io, I guess I "own it" now... I will look into this.

2021-02-23 12:41 UTC, iherman commented
> > I will also note that the diagram in the data model section is now wrong (because it contemplates `@context` in the DID Document data model, which is now incorrect).
> 
> Because I have re-created this diagram in draw.io, I guess I "own it" now... I will look into this.

See https://github.com/w3c/did-core/pull/692.

2021-02-23 16:22 UTC, peacekeeper commented
Hmm this really becomes harder to draw now, but how do people feel about this?

![Screenshot from 2021-02-23 17-19-19](https://user-images.githubusercontent.com/290941/108873580-8eebef00-75fb-11eb-82f2-2df8b673c3cc.png)

2021-02-23 23:24 UTC, talltree commented
@peacekeeper I like this version very much. You did a good job of adding representation-specific entries. Spot on. Nice job.

2021-02-23 23:37 UTC, OR13 commented
@peacekeeper that picture is better, but is till not completely in line with the spec... for example:

https://w3c.github.io/did-core/#data-model

production and consumption are defined in terms of the "DID Document entries"... so sadly... this diagram is not consistent with those section... I hate to be pedantic, but this is still a problem.

production and consumption are not defined in term of "representation specific entries"... 

They are defined in terms of DID Document entries... The new picture implies that representation specific entries are some how no did document entries... if thats true the production and consumption sections need to be rewritten.

![https://w3c.github.io/did-core/diagrams/diagram-did-document-entries.svg](https://w3c.github.io/did-core/diagrams/diagram-did-document-entries.svg)

2021-02-24 00:10 UTC, peacekeeper commented
@OR13: After merging @msporny 's PR https://github.com/w3c/did-core/pull/679, the section on Production and Consumption now says

_A conforming producer MUST take a DID document data model and a representation-specific entries map as input into the production process._

I.e. the produce function now takes two maps as input, and the consume function returns two maps as output. That's what the new diagram in this PR here https://github.com/w3c/did-core/pull/596#issuecomment-784323901 is trying to show.

I agree this is now inconsistent with the data model diagram. @iherman is working on updating that in https://github.com/w3c/did-core/pull/692.

2021-02-25 17:09 UTC, OR13 commented
related: https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-11-05-did#resolution4

2021-02-25 17:11 UTC, OR13 commented
I would approve this, if the upper left hand corner looked like: 

![https://w3c.github.io/did-core/diagrams/diagram-did-document-entries.svg](https://w3c.github.io/did-core/diagrams/diagram-did-document-entries.svg)

2021-02-26 11:07 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-02-25-did-topic#section1) on 2021-02-25

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 1. Diagrams 

_See github pull request [#596](https://github.com/w3c/did-core/pull/596), [#597](https://github.com/w3c/did-core/pull/597)._




**Markus Sabadello:** there are two open PRs with diagrams that I was working on  
… one is [#596](https://github.com/w3c/did-core/pull/596)  
… on production and consumption  
… one on resolve and resolveRepresentation  
… 597, I have not worked on updating that yet  
… I have tried to update the production and consumption one  
… I came up with this version  
… latest attempt maybe not perfect, but how close is it to what people want to see?  
… tries to implement this separation of the maps that we're saying we're passing into the production function and getting out of the consumption function  
… and the did document data model and representation specific entries as a separate map  

**Manu Sporny:** this is not necessarily aligned with where I thought we were going  
… its' confusing because the bottom one looks like it's just using the representation specific entries  
… some changes  
… if you take did document data model at the top and figure out how to move it into that dashed box  
… and representation specific entries, strike json-ld, and move into the dashed box below  
… and do a larger dashed box around both  
… and have produce and consume go from that would solve the issue for me  

**Markus Sabadello:** *live edits diagram*  

**Manu Sporny:** it does dodge some of the questions, but addresses my concern, if everyone agrees  

**Markus Sabadello:** I can live with it  

> *Ivan Herman:* +1 with these changes

**Orie Steele:** what was proposed is consistent with the current diagram that has been merged into did core  
… the upper left hand box with dashed lines is already represented in did core under the data model section  
… i'd be fine if we used the existing diagram and didn't add another diagram that in some ways conflicts  
… the existing diagram we have in did core is acceptable for me  
… as a result of consumption  
… i'm struggling why we should show different pictures of the same data model  
… almost there, stop representing the data model differently in different diagrams  
… use the same diagram for each of them  

> *Shigeya Suzuki:* While I almost agree to the diagram... +1 to Orie's opinion

> *Shigeya Suzuki:* (reuse same diagram on same concept)

**Ted Thibodeau Jr.:** i'm concerned that surrounding dashed box suggests that those representation specific entries are part of all of the productions  

**Ivan Herman:** orie, when you talk about the diagram in the spec right now, are you talking about that one or the change that is part of another PR?  

**Manu Sporny:** merged few minutes ago  

**Ivan Herman:** you make our life difficult :-)  

> *Orie Steele:* I mean use this diagram: [https://w3c.github.io/did-core/#data-model](https://w3c.github.io/did-core/#data-model)

> *Orie Steele:* :)

**Manu Sporny:** I like where orie is going with this, we do have something already, can we reuse that  
… that would be better I think  

**Ivan Herman:** there is a difference, what markus is doing is with code extract which here is not the case  
… reusing the same style and colours would make sense  
… but it's not the same diagram  
… here we list some of the core properties, not all  

> *Shigeya Suzuki:* +1 to Ivan

> *Justin Richer:* +1 this is not the same diagram, this is how we get TO that diagram (and from it)

> *Ted Thibodeau Jr.:* +1 these are different diagrams for different purposes

> *Brent Zundel:* +1

**Markus Sabadello:** also some similarities and differences  
… both show the data model, but this one here that ivan made is intended to be more generic and higher level, whereas the other has a concrete example  
… the other difference is that this is showing the concepts of core things and registered extensions and unregistered extensions, which are irrelevant in the other diagram which is about production and consumption  

> *Drummond Reed:* +1 to the diagram we are seeing now on "production and consumption"

**Markus Sabadello:** using similar colours and style, I'd be happy to make an attempt to do that  

**Manu Sporny:** orie, would you be okay with that? I buy the argument that they're slightly different.. would you be okay that kind of set up?  

**Orie Steele:** we have a resolution that hasn't made it into the spec yet around ignoring and consuming properties  
… somewhat related to what we're talking about here  
… this diagram that's showing concrete production and consumption for three representations  
… aligning the colours is a good idea  
… dangerously to represent the adm abstractly and concretely in slightly different ways  
… an issue of colouring and consistency  
… and boxes coloured one way in the abstract sense, should show how properties are preserved during consumption should show up in those boxes  
… when you consume your properties are going into one of many different coloured boxes, and when you produce they're coming out of the coloured boxes and going into one representation  
… I like the image in did core right now, and this one doesn't look like that  
… the subtle differences are harmful  
… we should use the same labels  
… representation specific entries, core representations specific entries  
… all of the term labels should be the same  

**Manu Sporny:** I agree with what orie is saying in general  
… is markus willing to give that a shot?  
… Ted raised that it make sit look like you use all those things to produce and consume  
… that's why I was saying there's a bit of a handwave that is okay  
… you can  

> *Orie Steele:* For the record, I am fine with the "content" of the diagram, just concerned about colors / labels

**Manu Sporny:** nothing to say that an application can't go into these boxes and modify them between production and consumption  
… I might consume json-ld, and if I know i'm going to produce json and my application feels strongly about removing @context it has the choice of doing that  
… we don't have anything in the spec that says you can't  
… we suggest that you should preserve everything  
… but apps can process these boxes for their own reasons  
… in consumption we say you have to preserve it  
… but we don't say you have to all the way through to production  
… you can modify them between those two  
… thats why we're handwaving a bit over this  
… I think that's okay because we need to get something that we're more or less okay with, otherwise this is going to keep getting blocked  

> *Orie Steele:* For example, you are not required to preserve prototype pollution or sql injection attacks :)

**Markus Sabadello:** agree that what we have now would allow both  
… it would allow having @context int he representations specific entries then producing plain json, and including `@context` there though personally I don't like it I think it's allowed and possible with the spec language  
… what I could also do is what we discussed before to split this up into multiple diagrams where we show different flows or different ways of using this  
… first consumption, then production  
… sometimes `@context` is there, sometimes it's not  
… I'd rather have one diagram  

**Brent Zundel:** feels like we have consensus on direction  
… I'd also rather have one diagram  
… opposition to moving on to testing?  

> *Orie Steele:* Also for the record, when you advocate for producing application/did+json without an @context, you are advocating for incompatibility / non-interoperability with JSON-LD verifiable credentials.

</details>

2021-02-26 13:12 UTC, TallTed commented
@OR13 
> ^ the data model must be presented consistently.

"Consistently" does not necessarily mean "identically", at least, not in any dictionary with which I'm familiar.

The two illustrations serve different purposes, and therefore show different perspectives of the same thing, which perspectives are not inconsistent with each other, in my opinion.  In yesterday's call, it sounded to me like most others are in agreement with me on this.

Perhaps you can explain how you see the two to be in disagreement with each other, which might help us figure out how to communicate the different perspectives, serve the different purposes, without that apparent disagreement?

2021-03-01 02:08 UTC, msporny commented
I'm running out of time to merge this PR before freeze this coming Monday COB ET. I need an update @peacekeeper -- ETA? If we can't get this in before CR, it's not a big deal, it's editorial, it can go in after we're in CR.

2021-03-01 12:28 UTC, peacekeeper commented
I pushed an updated version, based on recent conversations.

Changes:
- More aligned in style and color with the diagram in the ["Data Model" section](https://w3c.github.io/did-core/#data-model).
- Now shows how two different maps are involved the production/consumption process.

![diagram-production-consumption](https://user-images.githubusercontent.com/290941/109497020-bb878700-7a91-11eb-9183-c0560d0497ba.png)

2021-03-01 14:40 UTC, OR13 approved these changes

2021-03-01 21:48 UTC, msporny approved these changes

2021-03-01 21:49 UTC, msporny commented on index.html
> +and consumed, including in JSON, JSON-LD, and CBOR.">
We'll need to fix this description. Imagine you can't see, and you read this... have you learned the same thing that someone with sight has? If not, the description needs improvement. :)

2021-03-01 21:50 UTC, msporny approved these changes
We'll need to fix the alt text, merging due to time constraints.

2021-03-01 21:51 UTC, merged