Fix editorial issues in Core Properties section.
w3c/did-core pull request #630
Opened 2021-02-12 20:32 UTC by msporny

2021-02-12 20:41 UTC, brentzundel approved these changes

2021-02-13 09:07 UTC, rhiaro approved these changes

2021-02-13 09:07 UTC, rhiaro commented on index.html
> +    </p>
```suggestion
    </p>
    <p class="note" title="Property names used in maps of different types">
The property names <code>id</code>, <code>type</code>, and
<code>controller</code> can be present in maps of different types
with possible differences in constraints.
    </p>
```

With the "three classes of core properties" text removed, "classes" here no longer reads well.

2021-02-14 14:47 UTC, peacekeeper approved these changes
I agree with the simplification here and the removal of the "three classes of core properties" language (and with @rhiaro 's comment on that).

If possible we should wait for @iherman 's review since I think he wrote most of this section.

2021-02-14 15:18 UTC, iherman requested changes
I have no problems with the simplification of the section; it was mostly an introductory paragraph for the tables with the properties.

However. The change also removed the note whereby in the DID model, the order of the items in an ordered set are irrelevant. What this means is that, if we follow INFRA, the order of, say, verification methods has a meaning (which is not the case). If order is meaningful than the vocabularies and the constraints are also to be re-done, using RDF lists instead of just repeating property values. 

I just checked and the note was the only place in the document where this fact was mentioned. This note should be reinstated in the text.

2021-02-14 15:59 UTC, msporny commented
> However. The change also removed the note whereby in the DID model, the order of the items in an ordered set are irrelevant.

The statement was moved to a separate section in the specification in PR #631 -- see https://github.com/w3c/did-core/pull/631/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R1276

2021-02-14 16:12 UTC, iherman commented
> The statement was moved to a separate section in the specification in PR #631 -- see https://github.com/w3c/did-core/pull/631/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R1276
> 
> PS: I'm really glad that reviewers are paying attention to and are catching these potential oversights. :)

Sigh... Such tricks make our life difficult 😄

I am fine merging this PR *and* #631 together... 😉

2021-02-14 16:15 UTC, msporny commented
@iherman wrote:
> Such tricks make our life difficult smile

Just making sure everyone is paying attention... :P

2021-02-14 20:03 UTC, iherman approved these changes

2021-02-16 14:46 UTC, merged

2021-02-16 14:49 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.