Add a diagram depicts DID URL dereferencing
w3c/did-core pull request #648
Opened 2021-02-15 11:49 UTC by shigeya

Added in Sec 8.2. DID URL Dereferencing.

Place prior to the function signature. Small amount of text added.
![did_url_dereference_overview](https://user-images.githubusercontent.com/69672/107942792-179cd680-6fcf-11eb-966f-9e589d632369.png)

Attached is the added diagram for review convinience. 

Note: I've adjusted placement of properties inside DID document due to readability. May need to update other figure to match to this version.

2021-02-15 12:22 UTC, iherman commented
I am a bit bothered by the relationship between a DID URL's fragment and the DID document. The diagram suggests that even if my DID URL looks like `did:ex:12334/mypath?myQuery=foo#myFragment` then `myFragment` identifies something in a DID Document. But I believe that is not correct: the specification does _not_ say that `did:ex:12334/mypath?myQuery=foo` is necessarily a DID document. It can be any addressable resource under the sun, as long as it has a media type.

The diagram is of course correct for DID URL-s of the form `did:ex:12334#myFragment`.

I must admit I have no idea how to express this in a diagram (if I am right, that is)...

2021-02-15 13:08 UTC, shigeya commented
@iherman That's true.

I don't have reasonable answer, but one of the way to address this is to have diagrams express examplar relationships with actual values. I think that might be a useful thing to add as supplemental materials. Possibly in FAQ?

2021-02-15 13:22 UTC, iherman commented
> @iherman That's true.
> 
> I don't have reasonable answer, but one of the way to address this is to have diagrams express examplar relationships with actual values. 

Another way is to "annotate" the diagram visually. For example (I am not sure that works!) the relevant arrow may be, say, dashed, and add a "footnote" (on the diagram, saying that the arrow is valid if both path and query are empty). I am not sure how this would look like, though...

2021-02-15 14:42 UTC, OR13 commented
> the specification does _not_ say that `did:ex:12334/mypath?myQuery=foo` is necessarily a DID document.

Th specification sorta says that `did:ex:12334/mypath?myQuery=foo` is NEVER a DID Document.... in the sense that the `id` field of a DID Document is a DID and not a DID URL.... When, how  or if a `path` and `query` are handled remain great mysteries and likely a large source of bugs and implementation discrepancies to come.

2021-02-15 14:48 UTC, OR13 approved these changes

2021-02-15 15:27 UTC, peacekeeper commented
> Th specification sorta says that `did:ex:12334/mypath?myQuery=foo` is NEVER a DID Document.... in the sense that the `id` field of a DID Document is a DID and not a DID URL....

Just because the "id" field of the DID document MUST be a DID doesn't mean that a DID URL with path and query can't dereference to a DID document. Of course there are a number of potential challenges with this (as discussed in the mega--thread at https://github.com/w3c/did-core/issues/337), but I don't think we should make assumptions at this point in time with regard to the range of outputs of the derefence() function.

> When, how or if a `path` and `query` are handled remain great mysteries and likely a large source of bugs and implementation discrepancies to come.

We intentionally specified the contracts (but not implementation details) of the resolution and dereferencing functions. Other specifications can define more concrete dereferencing rules such as `IF did url contains path X and query parameter Y, THEN return resource of certain TYPE`.

Putting too much of this into DID Core would be a bit like defining `.well-known` or `/cgi-bin/` or `.htaccess` in the core HTTP specification.

2021-02-15 15:49 UTC, iherman requested changes
The differences in opinion between https://github.com/w3c/did-core/pull/648#issuecomment-779265121 and https://github.com/w3c/did-core/pull/648#issuecomment-779293513 just reinforces my opinion that the diagram should be clearer (as said in https://github.com/w3c/did-core/pull/648#issuecomment-779188286)

2021-02-15 19:42 UTC, shigeya commented
Okay, then, I'm trying to blur how DID URL looks and it possibly dereferences to either a DID document, a resource in a DID document, or an external resource. How do you think?

I've not committed this change to the PR yet.

I'm thinking of swapping the top two components with the bottom components since it may be natural.

![did_url_dereference_overview-trial1](https://user-images.githubusercontent.com/69672/107987372-3f149300-7011-11eb-9139-c64efb1d28ad.png)

2021-02-15 20:10 UTC, shigeya commented
Swapped the top and the bottom elements

![did_url_dereference_overview-trial2](https://user-images.githubusercontent.com/69672/107989261-45a50980-7015-11eb-8b7d-28840baaa358.png)

2021-02-16 00:02 UTC, shigeya commented
As an experiment, I converted the above experimental diagram into [diagrams.net](https://www.diagrams.net) (previously known as draw.io) `.drawio` format and placed it here:

https://github.com/shigeya/did-core/blob/shigeya-diagrams-work/diagrams/shigeya-work/did_url_dereference_overview-trial3.drawio

I could convert with a small number of adjustments.

2021-02-16 05:53 UTC, iherman commented
@shigeya what is the meaning of having two arrows from a DID URL to a DID Document (dereferencing to a resource and  dereferencing to a did document)? The first one seems to be superfluous to me.

2021-02-16 06:08 UTC, shigeya commented
@iherman I usually don't draw two arrows this way. There are two possible dereference results, so I thought two arrows might help distinguish two potential cases -- without showing possible URLs dereference.

Showing a single arrow with a text `dereferences to a DID document or a resource` maybe better?

2021-02-16 07:59 UTC, iherman commented
> @iherman I usually don't draw two arrows this way. There are two possible dereference results, so I thought two arrows might help distinguish two potential cases -- without showing possible URLs dereference.
> 
> Showing a single arrow with a text `dereferences to a DID document or a resource` maybe better?

But why referring to a resource dereferencing towards a DID document, when we also have a separate arrow pointing to a resource below? What about (1) relabeling the box currently "External Resource" to simply "Resource" and remove the one pointing to a DID Document as a resource?

2021-02-16 15:50 UTC, shigeya commented
@iherman Thanks. See below. It's more uncomplicated and more straightforward. But from my perspective, it is now somewhat unclear on the case which points to DID document's property  (`did:ex:12334#myFragment` ) since the resource seems external to the DID document. Maybe adding some text to the `refers to` arrow helps?

![did_url_dereference_overview-trial4](https://user-images.githubusercontent.com/69672/108085691-f3b5bf80-70b8-11eb-91e3-0d26ae1b9ccc.png)

2021-02-16 15:57 UTC, iherman commented
> It's more uncomplicated and more straightforward. But from my perspective, it is now somewhat unclear on the case which points to DID document's property (`did:ex:12334#myFragment` ) since the resource seems external to the DID document. Maybe adding some text to the `refers to` arrow helps?

The problem is that many details of the DID URL dereferencing is (deliberately) underspecified, so when you say it is "unclear" there is good reason for it :-) 

In my view we should stop here. The diagram is cleaner now, but it does not replace a specification...

@peacekeeper wdyt?

2021-02-16 17:07 UTC, shigeya commented
😅

2021-02-16 18:41 UTC, brentzundel approved these changes

2021-02-16 18:41 UTC, brentzundel commented on index.html
> +external resources.
```suggestion
DIDs resolve to DID documents; DID URLs contain a DID; DID URLs dereference to
DID document fragments or external resources.
```

2021-02-16 19:04 UTC, TallTed commented
> `DID URLs dereference to DID document fragments or external resources`

But the diagram now says `DID URLs dereference to [the entire] DID document or to [external] resources`.  Why do I include `[external]`?  Because the **Resource** oval is outside the **DID document** box.

Is there a way with the current drawing tools to make the **Resource** oval slightly overlap the **DID document** box?  Maybe rotate the oval (not the label) 90°?  This would require no additional arrows, shapes, or labels, and would, I think, communicate that **Resource** might be external *or* within the **DID document**.

2021-02-17 05:11 UTC, shigeya commented
> But the diagram now says `DID URLs dereference to [the entire] DID document or to [external] resources`. Why do I include `[external]`? Because the **Resource** oval is outside the **DID document** box.

Yes, that was the original intention.

> Is there a way with the current drawing tools to make the **Resource** oval slightly overlap the **DID document** box? Maybe rotate the oval (not the label) 90°? This would require no additional arrows, shapes, or labels, and would, I think, communicate that **Resource** might be external _or_ within the **DID document**.

I can, and I also thought about overlapping as an option.
But if I move the resource oval,  is it okay to omit possible references to external resources?

It's a never-ending rabbit hole. I knew it!

So, one of the possible solution, as I wrote is:
> I don't have reasonable answer, but one of the way to address this is to have diagrams express examplar relationships with actual values. I think that might be a useful thing to add as supplemental materials. Possibly in FAQ?

I mean, showing relationships based on actual DID URL example, possibly in multiple figures. Maybe I need to show them for discussion.

2021-02-17 06:18 UTC, iherman commented
> > I don't have reasonable answer, but one of the way to address this is to have diagrams express examplar relationships with actual values. I think that might be a useful thing to add as supplemental materials. Possibly in FAQ?
> 
> I mean, showing relationships based on actual DID URL example, possibly in multiple figures. Maybe I need to show them for discussion

Yes, maybe that is a way forward. Putting this mess (or rabbit hole:-) into one diagram may simply be unmanageable.

2021-02-17 14:13 UTC, msporny commented
@shigeya and @iherman -- I'm holding off on pulling in this PR because it seems there is still active discussion. Please tell me when the PR is ready to be merged.

2021-02-17 21:57 UTC, rhiaro commented
Minor comment on the diagram in https://github.com/w3c/did-core/pull/648#issuecomment-779926351 - "DID document-relative fragment dereference" should be "DID document - relative fragment dereference" so it doesn't look like "document-relative" is a hyphenated word. Maybe with a line break after "DID document", and/or a line break before "dereference".

2021-02-25 16:52 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, seems to have settled, merging.

2021-02-25 16:53 UTC, merged

2021-02-25 17:07 UTC, TallTed commented
> Minor comment on the diagram in [#648 (comment)](https://github.com/w3c/did-core/pull/648#issuecomment-779926351) - "DID document-relative fragment dereference" should be "DID document - relative fragment dereference" so it doesn't look like "document-relative" is a hyphenated word. Maybe with a line break after "DID document", and/or a line break before "dereference".

It does not appear that this comment was addressed (or perhaps I've missed an update somewhere).

I would suggest changing the `-` (hyphen) to ` — ` (space-mdash-space), possibly followed by a line-break. (I'm not sure I'm clear on what this particular label is meant to say, so I can't suggest new words, which might be even better than my preceding suggestion.)

2021-02-25 23:32 UTC, shigeya commented
> It does not appear that @rhiaro's comment was addressed.
> I would suggest changing the - (hyphen) to  —  (space-mdash-space), possibly followed by a line-break. (I'm not sure I'm clear on what this particular label is meant to say, so I can't suggest new words, which might be even better than my preceding suggestion.)

Oops. That's my fault. Also, I understand @TallTed's suggestion, thanks.

I guess I need to create another PR to address this since this branch is already merged?

2021-02-26 01:52 UTC, shigeya commented
Also, I forgot to add `.drawio` file. creating PR..