Substantive updates to DID Method Requirements section.
w3c/did-core pull request #666
Opened 2021-02-17 23:43 UTC by msporny

This is a big rework of the methods section. Almost all normative requirements were kept, but reworded slightly or reduced in size due to other overlapping normative statements. I've marked these changes as substantive because, although none of the changes would affect software implementations, some of the changes would affect what was expected to be written by DID Method Specification authors.

2021-02-18 01:04 UTC, OR13 approved these changes

2021-02-18 03:57 UTC, TallTed commented on index.html
> +media type value is <code>application/did+json</code>: the data structure
```suggestion
media type value is <code>application/did+json</code>, then the data structure
```

2021-02-18 03:58 UTC, TallTed commented on index.html
>  being consumed is a <a>DID document</a> and the root element MUST be a <a
```suggestion
being consumed is a <a>DID document</a>, and the root element MUST be a <a
```

2021-02-18 04:00 UTC, TallTed commented on index.html
> +addition, to defining a specific <a>DID scheme</a>, a <a>DID method</a>
```suggestion
addition to defining a specific <a>DID scheme</a>, a <a>DID method</a>
```

2021-02-18 04:01 UTC, TallTed commented on index.html
> +method-specific DID Syntax are:
```suggestion
method-specific DID Syntax are as follows:
```

2021-02-18 04:03 UTC, TallTed commented on index.html
> +by itself.
```suggestion
method</a>. The <code>method-specific-id</code> value itself might be globally
unique.
```

2021-02-18 04:06 UTC, TallTed commented on index.html
> +Registries [[?DID-SPEC-REGISTRIES]].
```suggestion
To reduce the chances of <code>method-name</code> conflicts, a <a>DID method</a>
specification SHOULD be registered in the DID Specification Registries
[[?DID-SPEC-REGISTRIES]].
```

2021-02-18 04:12 UTC, TallTed commented on index.html
> +method operations are:
```suggestion
method operations are as follows:
```

2021-02-18 04:19 UTC, TallTed commented on index.html
> +might:
```suggestion
might &mdash;
```

2021-02-18 04:28 UTC, TallTed commented on index.html
> +out-of-band mechanism.
```suggestion
not use the <a>DID document</a> for this decision at all, and depend on an
out-of-band mechanism, instead.
```

2021-02-18 04:29 UTC, TallTed commented on index.html
> +<em>Security Considerations</em> section are:
```suggestion
<em>Security Considerations</em> section are as follows:
```

2021-02-18 04:32 UTC, TallTed commented on index.html
> +replay, message insertion, deletion, modification, denial of service,  storage
```suggestion
replay, message insertion, deletion, modification, denial of service, storage
```

2021-02-18 04:37 UTC, TallTed commented on index.html
> +or network amplification, and man-in-the-middle.
```suggestion
The Security Considerations section MUST document the following forms of attack
for the <a>DID</a> operations defined in the <a>DID method</a> specification:
eavesdropping, replay, message insertion, deletion, modification, denial of
service, storage or network amplification, and man-in-the-middle. Other known
forms of attack SHOULD also be documented.
```

2021-02-18 04:39 UTC, TallTed commented on index.html
> +or network amplification, and man-in-the-middle.
Yeah, I added a normative statement... I think it is in the spirit of the section, and I can't think of any other way to say it that doesn't drastically weaken what *should* be a requirement.

2021-02-18 04:44 UTC, TallTed commented on index.html
> +integrity only, confidentiality, or endpoint authentication.
```suggestion
protected and by what protections, and it SHOULD give an indication of the
sorts of attacks to which the cryptographic protection is susceptible. Some
examples are integrity only, confidentiality, and endpoint authentication.
```

2021-02-18 04:46 UTC, TallTed commented on index.html
>  discussed in relation to denial of service.
```suggestion
Where <a>DID methods</a> use peer-to-peer computing resources, such as with all
known <a>DLTs</a>, the expected burdens of those resources SHOULD be discussed
in relation to denial of service.
```

2021-02-18 04:48 UTC, TallTed requested changes
A bunch of minor adjustments, a couple not-so-minor...

2021-02-19 20:24 UTC, msporny commented
Substantive, multiple reviews, changes requested and made, no objections, merging.

2021-02-19 20:24 UTC, merged