Re-writing the intro paragraph of §5.1
w3c/did-core pull request #683
Opened 2021-02-19 11:19 UTC by iherman

The introductory paragraph in [§5.1](https://w3c.github.io/did-core/#identifiers) says:

> It is necessary to learn the identifiers used within a DID document to refer to the DID subject and the DID controller, as well as any alternate identifiers that might also be used to reference the DID subject. The following section elaborates on the mechanisms the DID document data model provides for so doing.

I was not fully sure  what this paragraph really tries to say and, in any case, "necessary to learn" is not an acceptable style for a specification. Also, the generic statement on identifiers is not accurate: identifiers in a DID document are also used to identify verification methods or services.

The PR proposes an alternate formulation based on my understanding (which may be entirely wrong!).

2021-02-19 14:27 UTC, OR13 approved these changes

2021-02-19 20:43 UTC, msporny commented on index.html
> +        A <a>DID document</a> must include identifiers referring to the <a>DID subject</a>, as well as to the <a>DID controller</a>. While the primary mechanism is to use the <a href="#did-syntax">DI
Wrap to 80 characters, no indents, please. Long lines make diff-reading /very/ difficult and also complicate suggesting edits in Github.

2021-02-19 20:43 UTC, msporny requested changes
Wrap to 80 characters, no indents, please. Long lines make diff-reading /very/ difficult and also complicate suggesting edits in Github.

2021-02-19 23:13 UTC, brentzundel commented on index.html
> +        A <a>DID document</a> must include identifiers referring to the <a>DID subject</a>, as well as to the <a>DID controller</a>. While the primary mechanism is to use the <a href="#did-syntax">DI
```suggestion
It is necessary for <a>DID documents</a> t/o include identifiers referring to
the <a>DID subject</a>, as well as to the <a>DID controller</a>. While the
primary mechanism is to use the <a href="#did-syntax">DID Syntax</a>, the
<a>DID document</a> could also include alternate identifiers to reference the
<a>DID subject</a>. The following section elaborates on the mechanisms the
<a>DID document</a> data model provides for so doing.
```

2021-02-19 23:13 UTC, brentzundel commented on index.html
> +        A <a>DID document</a> must include identifiers referring to the <a>DID subject</a>, as well as to the <a>DID controller</a>. While the primary mechanism is to use the <a href="#did-syntax">DI
suggestion fixes line length and removes language that could be considered normative.

2021-02-21 17:02 UTC, rhiaro approved these changes
It seemed a bit long winded, and the part about DID syntax was hard to follow, and in attempting to trim it down my suggested edit replaces the whole thing...

2021-02-21 17:02 UTC, rhiaro commented on index.html
> +<a>DID document</a> data model provides for so doing.
```suggestion
This section describes the mechanisms by which <a>DID documents</a>
include identifiers for <a>DID subjects</a> and <a>DID controllers</a>.
```

2021-02-21 21:09 UTC, msporny commented on index.html
> +It is necessary for <a>DID documents</a> t/o include identifiers referring to
Used the alternate wording.

2021-02-21 21:10 UTC, msporny approved these changes

2021-02-21 21:10 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2021-02-21 21:10 UTC, merged