Post-CR Changes on ECHIDNA (DO NOT MERGE THIS BEFORE CR PUBLICATION)
w3c/did-core pull request #711
Opened 2021-03-11 09:52 UTC by iherman

With the CR publication, the usage of ECHIDNA changes (see [separate ECHIDNA page](https://github.com/w3c/echidna/wiki/CR-publication-workflow)):

1. Any editorial CR update can be made on a CR via ECHIDNA
2. A substantial CR update must require a Director's approval, and has to go through the staff contact and the W3C Webmaster

This PR makes the necessary changes on the ECHIDNA setup.

2021-03-11 12:11 UTC, deniak requested changes
The documentation is actually no longer up-to-date. With process 2020, we now have a better way to differentiate the 2 types of CR (CR Snapshot and CR Draft). For updates that are not substantive, it should be a CR draft.

2021-03-11 12:11 UTC, deniak commented on .travis.yml
> +  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN" --data="editorial=true"
```suggestion
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
```

2021-03-11 12:11 UTC, deniak commented on ECHIDNA
> +index.html?specStatus=CR&shortName=did-core respec
```suggestion
index.html?specStatus=CRD&shortName=did-core respec
```

2021-04-30 20:05 UTC, msporny approved these changes

2021-04-30 20:05 UTC, msporny commented
Purely editorial, merging.

2021-04-30 20:06 UTC, merged