Fix editorial issues with equivalence properties.
w3c/did-core pull request #749
Opened 2021-05-23 22:14 UTC by msporny

Partial editorial cleanup to appendices tracked as issue #728.

2021-05-23 23:30 UTC, csuwildcat requested changes
I don't understand why there are any special security issues with equivalent/canonical, because they are Method-specified. There's no difference in a Method resolving the initial ID or the equivalent/canonical variants; trust in the Method is the same wither way. The unique security issues are with alsoKnownAs, so I don't agree with them being lumped under this wording.

2021-05-24 16:35 UTC, brentzundel approved these changes

2021-05-25 16:46 UTC, csuwildcat commented
@msporny the most significant nit is with the first part of the text. Shouldn't it say something like: "Given the `equivalentId` and `canonicalId` properties are determined by and within Methods themselves, they are subject to the same security guarantees a Method provides for the resolved ID itself, namely: if you trust a Method to properly resolve IDs in general, you trust the resolution of the IDs in these properties. The `alsoKnownAs` property is not Method-secured or guaranteed by Methods to be an accurate statement of equivalence by the controller of the resolved ID, thus they cannot be immediately relied upon without some Method-external validation procedure."

2021-05-25 19:48 UTC, msporny commented
> @msporny the most significant nit is with the first part of the text. Shouldn't it say something like: "Given the `equivalentId` and `canonicalId` properties are determined by and within Methods themselves, they are subject to the same security guarantees a Method provides for the resolved ID itself, namely: if you trust a Method to properly resolve IDs in general, you trust the resolution of the IDs in these properties. The `alsoKnownAs` property is not Method-secured or guaranteed by Methods to be an accurate statement of equivalence by the controller of the resolved ID, thus they cannot be immediately relied upon without some Method-external validation procedure."

Yes, I'd be fine w/ that language. Please simplify it to a high school reading level -- that's what these editorial passes are about. It takes quite a bit of effort to parse your statement above... it's has a lot of embellishment in it... please try to strip it down to it's most basic components/statements.

2021-05-26 05:18 UTC, kdenhartog approved these changes

2021-05-26 15:36 UTC, csuwildcat commented
How about this: "Given the equivalentId and canonicalId properties are determined by Methods themselves, the same security and accuracy guarantees that apply to the resolved ID present in the `id` field of a DID Document also apply to these properties. The `alsoKnownAs` property is not guaranteed to be an accurate statement of equivalence, and should not be relied upon without performing validation steps beyond the resolution of the DID Document."

2021-05-26 16:13 UTC, msporny commented
> How about this: "Given the equivalentId and canonicalId properties are determined by Methods themselves, the same security and accuracy guarantees that apply to the resolved ID present in the `id` field of a DID Document also apply to these properties. The `alsoKnownAs` property is not guaranteed to be an accurate statement of equivalence, and should not be relied upon without performing validation steps beyond the resolution of the DID Document."

Perfect. Do you mind doing a change suggestion on this PR to that effect?

2021-05-26 16:35 UTC, csuwildcat commented on index.html
> +<a>DIDs</a> that are asserted to be equivalent.
```suggestion
Given the <code><a>equivalentId</a></code> and <code><a>canonicalId</a></code> properties are determined by Methods themselves, the same security and accuracy guarantees that apply to the resolved ID present in the <code>id</code> field of a DID Document also apply to these properties. The <code><a>alsoKnownAs property is not guaranteed to be an accurate statement of equivalence, and should not be relied upon without performing validation steps beyond the resolution of the DID Document.
```

2021-05-30 15:01 UTC, msporny commented on index.html
> +<a>DIDs</a> that are asserted to be equivalent.
Accepted your change with one minor edit.

2021-05-30 15:01 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2021-05-30 15:01 UTC, merged