Editorial fixes to DID Correlation Risks section.
w3c/did-core pull request #760
Opened 2021-05-30 19:51 UTC by msporny

Partial editorial cleanup to appendices tracked as issue #728.

2021-06-01 14:21 UTC, TallTed commented on index.html
> +or to share it with a large number of parties, is when the <a
```suggestion
or to share it with multiple parties, is when the <a
```

2021-06-01 14:22 UTC, TallTed requested changes
Approved, with [one small change](https://github.com/w3c/did-core/pull/760/files#r643149243).

2021-06-01 19:40 UTC, brentzundel approved these changes

2021-06-08 01:01 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2021-06-08 01:01 UTC, merged