Speak to when a DID and DID Document start existing.
w3c/did-core pull request #765
Opened 2021-06-12 17:37 UTC by msporny

This PR has been raised to address #729. It elaborates on when a DID and DID Document begin to exist. /cc @Kalanamith

2021-06-13 08:44 UTC, kdenhartog approved these changes

2021-06-13 21:37 UTC, TallTed requested changes
I think these tweaks will increase clarity without changing meaning.

2021-06-13 21:37 UTC, TallTed commented on index.html
> +<a href="#creation-of-a-did"></a>.
```suggestion
specifications. The creation processes, and their timing, for <a>DIDs</a> and
<a>DID URLs</a> are described in <a href="#method-operations"></a> and
<a href="#creation-of-a-did"></a>.
```

2021-06-13 21:37 UTC, TallTed commented on index.html
> +generative such that a <a>DID</a> and a <a>DID Document</a> is generated by
```suggestion
generative, such that a <a>DID</a> and a <a>DID Document</a> are generated by
```

2021-06-13 21:37 UTC, TallTed commented on index.html
> +<a>representation</a>. Other <a>DID Methods</a> require the use of a
```suggestion
<a>representation</a>. Other <a>DID Methods</a> might require the use of a
```

2021-06-13 21:37 UTC, TallTed commented on index.html
> +<a>verifiable data registry</a> where the <a>DID</a> and <a>DID Document</a>
```suggestion
<a>verifiable data registry</a>, where the <a>DID</a> and <a>DID Document</a>
```

2021-06-13 21:37 UTC, TallTed commented on index.html
> +completed, as defined by the respective <a>DID Method</a>.
```suggestion
completed, as defined by the respective <a>DID Method</a>. Other processes
may be defined by the respective <a>DID Method</a>.
```

2021-06-14 12:11 UTC, rhiaro requested changes
and +1 to @TallTed's suggested changes

2021-06-14 12:11 UTC, rhiaro commented on index.html
> +generative such that a <a>DID</a> and a <a>DID Document</a> is generated by
```suggestion
method</a>. Some <a>DID methods</a>, such as <code>did:key</code>, are purely
generative such that a <a>DID</a> and a <a>DID document</a> is generated by
```

2021-06-14 12:11 UTC, rhiaro commented on index.html
> +<a>representation</a>. Other <a>DID Methods</a> require the use of a
```suggestion
<a>representation</a>. Other <a>DID methods</a> require the use of a
```

2021-06-14 12:11 UTC, rhiaro commented on index.html
> +<a>verifiable data registry</a> where the <a>DID</a> and <a>DID Document</a>
```suggestion
<a>verifiable data registry</a> where the <a>DID</a> and <a>DID document</a>
```

2021-06-14 12:11 UTC, rhiaro commented on index.html
> +completed, as defined by the respective <a>DID Method</a>.
```suggestion
completed, as defined by the respective <a>DID method</a>.
```

2021-06-14 14:10 UTC, TallTed commented
I don't think github will do the desired thing where our suggestions overlap, so I've blended @rhiaro's changes into mine, where they fit.  There will remain one or two upper-to-lower case letter shifts after applying all of mine, but applying @rhiaro's would then revert some of mine, unless those also get tweaked to include my changes.

Alternatively, it might be best to manually apply all the suggestions we both made.

2021-06-14 19:07 UTC, brentzundel approved these changes

2021-06-21 11:36 UTC, peacekeeper approved these changes
Agree with this PR and with tweaks by @TallTed and @rhiaro

2021-06-27 18:31 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2021-06-27 18:31 UTC, merged