Add links to use cases document. Consolidate other useful links.
w3c/did-core pull request #774
Opened 2021-07-10 21:54 UTC by msporny

2021-07-11 16:34 UTC, clehner approved these changes

2021-07-12 09:43 UTC, philarcher requested changes
Thanks very much for doing this @msporny, much appreciated. However, I'm going to be annoying and push for just a little more and, in doing so, hope to fix a small problem.

I suggest that the 4th paragraph of the introduction to the doc could be extended by a short sentence so that we have "... all without depending on a central authority to guarantee the continued existence of the identifier. These ideas are explored in the DID Use Cases document [[DID-USE-CASES]]."

This a) puts a link in the informative text rather then relying solely on the references section; b) uses SpecRef's database to insert the reference rather than the hand-edited link in the ReSpec config which, although it points to the correct URL, it uses author data from the CCG original.

2021-07-12 14:00 UTC, msporny commented
> Thanks very much for doing this @msporny, much appreciated. However, I'm going to be annoying and push for just a little more and, in doing so, hope to fix a small problem.
> 
> I suggest that the 4th paragraph of the introduction to the doc could be extended by a short sentence so that we have "... all without depending on a central authority to guarantee the continued existence of the identifier. These ideas are explored in the DID Use Cases document [[DID-USE-CASES]]."
> 
> This a) puts a link in the informative text rather then relying solely on the references section; 

We already have a link in the informative text, that's what this PR does:

https://github.com/w3c/did-core/pull/774/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R433-R437

I added your text as well, let me know if that's what you were going for?

b) uses SpecRef's database to insert the reference rather than the hand-edited link in the ReSpec config which, although it points to the correct URL, it uses author data from the CCG original.

Ah, yes, thank you and fixed in b6e0136f46e5fd3409769f94d06fa8cb8b98fd9a.

2021-07-12 14:10 UTC, philarcher approved these changes
Sorted, thank you.

2021-07-13 02:42 UTC, kdenhartog approved these changes

2021-07-13 12:40 UTC, rhiaro approved these changes

2021-07-13 15:56 UTC, dlongley approved these changes

2021-07-14 16:04 UTC, peacekeeper approved these changes

2021-07-17 17:43 UTC, merged

2021-07-17 17:43 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.