Fix serviceEndpoints maps link
w3c/did-core pull request #851
Opened 2024-03-05 17:15 UTC by KendallWeihe

Similar to https://github.com/w3c/did-core/pull/840

It was unclear to me if these should be maps (as they are) or [ordered maps](https://infra.spec.whatwg.org/#ordered-map)?

2024-03-05 18:42 UTC, davidlehn approved these changes

2024-03-25 19:27 UTC, decentralgabe approved these changes

2024-07-07 19:49 UTC, msporny commented
This PR attempts to change a date-stamped Recommendation -- we can't do that (change documents published in the past).

Instead, this change has been made in the main spec and the fix will go out in v1.1 (within weeks).

2024-07-07 19:51 UTC, msporny requested changes
This PR attempts to change a date-stamped Recommendation -- we can't do that (change documents published in the past). Our charter was just renewed a month ago, and so we're starting to process issues again, but we can't make the kind of change requested by this PR.

@KendallWeihe wrote:
> It was unclear to me if these should be maps (as they are) or [ordered maps](https://infra.spec.whatwg.org/#ordered-map)?

They are just maps, not ordered maps.

If this change hasn't already been made on the main spec, @KendallWeihe, can you please update this PR to do that instead?

2024-08-15 15:47 UTC, decentralgabe commented
Closing. Please open a follow up if there remains a problem in the core spec.

2024-08-15 15:47 UTC, closed without merging